Add optional recaptcha brute force protection
mattupstate/flask-security pull request #764
Opened 2018-03-06 01:33 UTC by gnordens

Hi,
This PR adds an optional recaptcha brute force protection to the login form (default is disabled).

Login attempts and last login attempt are tracked on each user and require two extra columns:
`last_login_attempt_at = db.Column(db.DateTime, default=db.func.current_timestamp(), nullable=False) 
  login_attempts = db.Column(db.Integer, default=0)`
A user is required to enter a recaptcha after security_recaptcha_max_attempts is reached. 
Login attempts are reset for a user after security_recaptcha_timeout is reached.

Related:
https://github.com/mattupstate/flask-security/issues/348
https://github.com/mattupstate/flask-security/issues/161

2018-03-07 12:40 UTC, Avamander commented
There already is optional recaptcha protection ability in flask-security. 
```python
from flask_wtf import RecaptchaField

class ExtendedRegistrerForm(forms.RegisterForm):
    recaptcha = RecaptchaField("Captcha")

security = Security(app, user_datastore,
                    confirm_register_form=ExtendedRegistrerForm)
```

You can override every form like this.

2018-03-12 17:33 UTC, gnordens commented
@Avamander 
I might be misunderstanding you (or missing something in the docs), but in your example aren't you simply overriding a form to include a recaptcha element? This PR instead looks to add a conditional recaptcha based on consecutive logins for a user rather than always displaying one. This is to reduce annoyance for the user trying to login while also adding some protection against brute force attacks. A similar feature has been request in the issues mentioned in the OP.

2018-03-12 17:50 UTC, Avamander commented
@gnordens Nothing stops you from counting login attempts in a custom user field inside the custom form and displaying the captcha based on that.

2018-06-28 08:33 UTC, jirikuncar commented
This looks like a change that should be handled per instance basis. Personally, I would rather store the login attempts in Redis rather than in SQL database.

2018-06-28 08:35 UTC, jirikuncar requested changes
Can you rewrite it as a tutorial that can be shown in docs?

2018-07-05 19:05 UTC, jirikuncar commented on flask_security/utils.py
> +    user.login_attempts = user.login_attempts + 1 if user.login_attempts else 1
The counter might not be very reliable for parallel attempts.

2018-07-05 19:09 UTC, jirikuncar commented
I am going to close the PR mainly for following reasons:

1. The ReCaptcha field can be already added to the custom forms;
2. The login counter is not very reliable in the current implementation;
3. Lack of tests.

If you find that 2. needs to be implemented in this package please send a separate PR.

2018-07-05 19:09 UTC, closed without merging